// ignore_for_file: prefer_initializing_formals
// The requested count is stored in a private field with a public getter that
// falls back to the number of questions, so an older saved record still reads
// correctly; a named parameter may not start with an underscore.
import '../features/setup/models/classroom_setup.dart';
import 'question.dart';

/// How hard the questions should be.
enum WorksheetDifficulty {
  easy(label: 'Easy', subtitle: 'For early learners'),
  medium(label: 'Medium', subtitle: 'For building skills'),
  advanced(label: 'Advanced', subtitle: 'For higher levels');

  const WorksheetDifficulty({required this.label, required this.subtitle});

  final String label;
  final String subtitle;

  static WorksheetDifficulty byName(String? name) {
    for (final WorksheetDifficulty v in values) {
      if (v.name == name) return v;
    }
    return WorksheetDifficulty.easy;
  }
}

/// The everyday objects a worksheet may draw.
///
/// Deliberately ordinary things a Jharkhand primary classroom already has.
/// Nothing here characterises a community; they are counting objects.
enum VisualExample {
  apples(label: 'Apples', hindiLabel: 'सेब', glyph: '🍎'),
  trees(label: 'Trees', hindiLabel: 'पेड़', glyph: '🌳'),
  animals(label: 'Animals', hindiLabel: 'जानवर', glyph: '🐄'),
  householdObjects(
    label: 'Household Objects',
    hindiLabel: 'बर्तन',
    glyph: '🏺',
  );

  const VisualExample({
    required this.label,
    required this.hindiLabel,
    required this.glyph,
  });

  final String label;

  /// The object's name in Hindi, so a Hindi question does not carry an English
  /// word in the middle of it.
  final String hindiLabel;

  /// Drawn as a font glyph rather than an image.
  ///
  /// A worksheet has to print on a phone with no connection, so nothing here
  /// may be a URL, and shipping four bitmaps for four shapes would be weight
  /// for nothing.
  final String glyph;

  static VisualExample? byName(String? name) {
    for (final VisualExample v in values) {
      if (v.name == name) return v;
    }
    return null;
  }
}

/// Where a worksheet's questions came from.
enum GenerationSource {
  /// Built on the device by the deterministic generator. Not a model.
  localOffline(label: 'Generated offline'),

  /// Produced by a real model through the backend.
  remoteAi(label: 'Generated by AI');

  const GenerationSource({required this.label});

  final String label;

  /// Whether a model wrote this. The "AI-generated" wording on the preview
  /// reads this and nothing else.
  bool get isAi => this == GenerationSource.remoteAi;

  static GenerationSource byName(String? name) {
    for (final GenerationSource v in values) {
      if (v.name == name) return v;
    }
    return GenerationSource.localOffline;
  }
}

/// A generated worksheet, ready to print or read out.
class Worksheet {
  const Worksheet({
    required this.id,
    required this.lessonId,
    required this.title,
    required this.learningOutcome,
    required this.classNumber,
    required this.subject,
    required this.teachingLanguage,
    required this.targetLanguage,
    required this.difficulty,
    required this.questions,
    required this.generatedAt,
    required this.generationSource,
    this.visualExamples = const <VisualExample>[],
    this.culturallyFamiliarExamples = true,
    this.teacherNotes,
    this.variant = 0,
    int? requestedQuestionCount,
  }) : _requestedQuestionCount = requestedQuestionCount;

  factory Worksheet.fromJson(Map<String, dynamic> json) => Worksheet(
        id: json['id'] as String,
        lessonId: json['lessonId'] as String,
        title: json['title'] as String,
        learningOutcome: json['learningOutcome'] as String,
        classNumber: json['classNumber'] as int,
        subject: ClassroomSubject.byName(json['subject'] as String?) ??
            ClassroomSubject.numeracy,
        teachingLanguage:
            TeachingMedium.byName(json['teachingLanguage'] as String?) ??
                TeachingMedium.hindi,
        targetLanguage:
            TargetLanguage.byName(json['targetLanguage'] as String?) ??
                TargetLanguage.santali,
        difficulty: WorksheetDifficulty.byName(json['difficulty'] as String?),
        questions: <WorksheetQuestion>[
          for (final dynamic q
              in json['questions'] as List<dynamic>? ?? const <dynamic>[])
            WorksheetQuestion.fromJson(q as Map<String, dynamic>),
        ],
        generatedAt: DateTime.parse(json['generatedAt'] as String),
        generationSource:
            GenerationSource.byName(json['generationSource'] as String?),
        visualExamples: <VisualExample>[
          for (final dynamic v
              in json['visualExamples'] as List<dynamic>? ?? const <dynamic>[])
            if (VisualExample.byName(v as String?) case final VisualExample e)
              e,
        ],
        culturallyFamiliarExamples:
            json['culturallyFamiliarExamples'] as bool? ?? true,
        teacherNotes: json['teacherNotes'] as String?,
        variant: json['variant'] as int? ?? 0,
        requestedQuestionCount: json['requestedQuestionCount'] as int?,
      );

  final String id;
  final String lessonId;
  final String title;
  final String learningOutcome;
  final int classNumber;
  final ClassroomSubject subject;

  /// Both languages come from the saved classroom, never from a constant.
  final TeachingMedium teachingLanguage;
  final TargetLanguage targetLanguage;

  final WorksheetDifficulty difficulty;
  final List<WorksheetQuestion> questions;
  final DateTime generatedAt;

  /// Read by every "AI-generated" label. A locally built worksheet never
  /// carries one.
  final GenerationSource generationSource;

  final List<VisualExample> visualExamples;
  final bool culturallyFamiliarExamples;
  final String? teacherNotes;

  /// Which regeneration pass produced this. Carried so the next Regenerate can
  /// ask for the following one instead of repeating this sheet.
  final int variant;

  /// How many questions were asked for.
  ///
  /// Kept separately from how many arrived, because those are the two numbers
  /// a validator has to compare: a generator that returned nine when ten were
  /// wanted is only detectable if the ten was written down.
  final int? _requestedQuestionCount;

  int get requestedQuestionCount =>
      _requestedQuestionCount ?? questions.length;

  int get questionCount => questions.length;

  bool get isAiGenerated => generationSource.isAi;

  String get languagePair =>
      '${teachingLanguage.label} + ${targetLanguage.label}';

  /// The question types this worksheet actually uses, read back off its own
  /// questions so a regeneration can ask for the same mix.
  Set<QuestionType> get questionTypes =>
      <QuestionType>{for (final WorksheetQuestion q in questions) q.type};

  /// How many questions carry the mother tongue as well.
  int get bilingualCount =>
      questions.where((WorksheetQuestion q) => q.isBilingual).length;

  bool get isFullyBilingual =>
      questions.isNotEmpty && bilingualCount == questions.length;

  Map<String, dynamic> toJson() => <String, dynamic>{
        'id': id,
        'lessonId': lessonId,
        'title': title,
        'learningOutcome': learningOutcome,
        'classNumber': classNumber,
        'subject': subject.name,
        'teachingLanguage': teachingLanguage.name,
        'targetLanguage': targetLanguage.name,
        'difficulty': difficulty.name,
        'questionCount': questionCount,
        'generatedAt': generatedAt.toIso8601String(),
        'isAiGenerated': isAiGenerated,
        'generationSource': generationSource.name,
        'visualExamples': <String>[
          for (final VisualExample v in visualExamples) v.name,
        ],
        'culturallyFamiliarExamples': culturallyFamiliarExamples,
        'teacherNotes': teacherNotes,
        'variant': variant,
        'requestedQuestionCount': requestedQuestionCount,
        'questions': <Map<String, dynamic>>[
          for (final WorksheetQuestion q in questions) q.toJson(),
        ],
      };
}
