"""initial schema

Revision ID: c740a4ab7b61
Revises: 
Create Date: 2026-08-30 02:07:04.132221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c740a4ab7b61'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessments',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('teacher_id', sa.String(length=64), nullable=True),
    sa.Column('lesson_id', sa.String(length=64), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('concepts', sa.JSON(), nullable=False),
    sa.Column('started_at', sa.String(length=64), nullable=False),
    sa.Column('finished_at', sa.String(length=64), nullable=False),
    sa.Column('answers', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessments_lesson_id'), 'assessments', ['lesson_id'], unique=False)
    op.create_index(op.f('ix_assessments_teacher_id'), 'assessments', ['teacher_id'], unique=False)
    op.create_table('classroom_sessions',
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('teacher_id', sa.String(length=64), nullable=True),
    sa.Column('lesson_id', sa.String(length=64), nullable=False),
    sa.Column('lesson_title', sa.String(), nullable=False),
    sa.Column('class_number', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=32), nullable=False),
    sa.Column('teaching_language', sa.String(length=16), nullable=False),
    sa.Column('target_language', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.String(length=64), nullable=False),
    sa.Column('ended_at', sa.String(length=64), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('saved_at', sa.String(length=64), nullable=True),
    sa.Column('sync_status', sa.String(length=16), nullable=False),
    sa.Column('turns', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index(op.f('ix_classroom_sessions_teacher_id'), 'classroom_sessions', ['teacher_id'], unique=False)
    op.create_table('classroom_setup',
    sa.Column('teacher_id', sa.String(length=64), nullable=False),
    sa.Column('school_name', sa.String(length=255), nullable=False),
    sa.Column('district_id', sa.String(length=64), nullable=True),
    sa.Column('district_name', sa.String(length=255), nullable=True),
    sa.Column('block_id', sa.String(length=64), nullable=True),
    sa.Column('block_name', sa.String(length=255), nullable=True),
    sa.Column('teaching_medium', sa.String(length=16), nullable=False),
    sa.Column('target_language', sa.String(length=16), nullable=False),
    sa.Column('class_level', sa.Integer(), nullable=False),
    sa.Column('subjects', sa.JSON(), nullable=False),
    sa.Column('setup_completed', sa.Boolean(), nullable=False),
    sa.Column('setup_completed_at', sa.String(length=64), nullable=True),
    sa.Column('pending_sync', sa.Boolean(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('teacher_id')
    )
    op.create_table('learning_outcomes',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=True),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('class_number', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=32), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=True),
    sa.Column('curriculum_reference', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_outcomes_class_number'), 'learning_outcomes', ['class_number'], unique=False)
    op.create_index(op.f('ix_learning_outcomes_subject'), 'learning_outcomes', ['subject'], unique=False)
    op.create_table('lessons',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('subject', sa.String(length=32), nullable=False),
    sa.Column('class_number', sa.Integer(), nullable=False),
    sa.Column('learning_outcome', sa.String(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('lesson_order', sa.Integer(), nullable=False),
    sa.Column('thumbnail_asset', sa.String(length=255), nullable=True),
    sa.Column('resource_ids', sa.JSON(), nullable=False),
    sa.Column('concepts', sa.JSON(), nullable=False),
    sa.Column('audio_resource_id', sa.String(length=255), nullable=True),
    sa.Column('worksheet_resource_id', sa.String(length=255), nullable=True),
    sa.Column('flashcard_resource_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lessons_class_number'), 'lessons', ['class_number'], unique=False)
    op.create_index(op.f('ix_lessons_subject'), 'lessons', ['subject'], unique=False)
    op.create_table('progress_events',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('teacher_id', sa.String(length=64), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('occurred_at', sa.String(length=64), nullable=False),
    sa.Column('lesson_id', sa.String(length=64), nullable=True),
    sa.Column('event_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_progress_events_teacher_id'), 'progress_events', ['teacher_id'], unique=False)
    op.create_index(op.f('ix_progress_events_type'), 'progress_events', ['type'], unique=False)
    op.create_table('schools',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('district_id', sa.String(length=64), nullable=True),
    sa.Column('district_name', sa.String(length=255), nullable=True),
    sa.Column('block_id', sa.String(length=64), nullable=True),
    sa.Column('block_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schools_code'), 'schools', ['code'], unique=True)
    op.create_table('support_reports',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('teacher_id', sa.String(length=64), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.String(length=64), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_support_reports_teacher_id'), 'support_reports', ['teacher_id'], unique=False)
    op.create_table('translations',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('lesson_id', sa.String(length=64), nullable=False),
    sa.Column('source_medium', sa.String(length=16), nullable=False),
    sa.Column('target_language', sa.String(length=16), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('spoken_text', sa.String(), nullable=True),
    sa.Column('provenance', sa.String(length=32), nullable=False),
    sa.Column('reviewed_by_speaker', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_translations_lesson_id'), 'translations', ['lesson_id'], unique=False)
    op.create_table('worksheets',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('teacher_id', sa.String(length=64), nullable=True),
    sa.Column('lesson_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('learning_outcome', sa.String(), nullable=False),
    sa.Column('class_number', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=32), nullable=False),
    sa.Column('teaching_language', sa.String(length=16), nullable=False),
    sa.Column('target_language', sa.String(length=16), nullable=False),
    sa.Column('difficulty', sa.String(length=16), nullable=False),
    sa.Column('questions', sa.JSON(), nullable=False),
    sa.Column('visual_examples', sa.JSON(), nullable=False),
    sa.Column('culturally_familiar_examples', sa.Boolean(), nullable=False),
    sa.Column('teacher_notes', sa.String(), nullable=True),
    sa.Column('variant', sa.Integer(), nullable=False),
    sa.Column('requested_question_count', sa.Integer(), nullable=True),
    sa.Column('generation_source', sa.String(length=16), nullable=False),
    sa.Column('generated_at', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_worksheets_lesson_id'), 'worksheets', ['lesson_id'], unique=False)
    op.create_index(op.f('ix_worksheets_teacher_id'), 'worksheets', ['teacher_id'], unique=False)
    op.create_table('teachers',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('mobile', sa.String(length=32), nullable=True),
    sa.Column('mobile_last4', sa.String(length=4), nullable=True),
    sa.Column('school_id', sa.String(length=64), nullable=True),
    sa.Column('school_code', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teachers_mobile'), 'teachers', ['mobile'], unique=True)
    op.create_index(op.f('ix_teachers_school_code'), 'teachers', ['school_code'], unique=False)
    op.create_index(op.f('ix_teachers_school_id'), 'teachers', ['school_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_teachers_school_id'), table_name='teachers')
    op.drop_index(op.f('ix_teachers_school_code'), table_name='teachers')
    op.drop_index(op.f('ix_teachers_mobile'), table_name='teachers')
    op.drop_table('teachers')
    op.drop_index(op.f('ix_worksheets_teacher_id'), table_name='worksheets')
    op.drop_index(op.f('ix_worksheets_lesson_id'), table_name='worksheets')
    op.drop_table('worksheets')
    op.drop_index(op.f('ix_translations_lesson_id'), table_name='translations')
    op.drop_table('translations')
    op.drop_index(op.f('ix_support_reports_teacher_id'), table_name='support_reports')
    op.drop_table('support_reports')
    op.drop_index(op.f('ix_schools_code'), table_name='schools')
    op.drop_table('schools')
    op.drop_index(op.f('ix_progress_events_type'), table_name='progress_events')
    op.drop_index(op.f('ix_progress_events_teacher_id'), table_name='progress_events')
    op.drop_table('progress_events')
    op.drop_index(op.f('ix_lessons_subject'), table_name='lessons')
    op.drop_index(op.f('ix_lessons_class_number'), table_name='lessons')
    op.drop_table('lessons')
    op.drop_index(op.f('ix_learning_outcomes_subject'), table_name='learning_outcomes')
    op.drop_index(op.f('ix_learning_outcomes_class_number'), table_name='learning_outcomes')
    op.drop_table('learning_outcomes')
    op.drop_table('classroom_setup')
    op.drop_index(op.f('ix_classroom_sessions_teacher_id'), table_name='classroom_sessions')
    op.drop_table('classroom_sessions')
    op.drop_index(op.f('ix_assessments_teacher_id'), table_name='assessments')
    op.drop_index(op.f('ix_assessments_lesson_id'), table_name='assessments')
    op.drop_table('assessments')
    # ### end Alembic commands ###